export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_CREDITS_SUCCESS = 'LOAD_CREDITS_SUCCESS';
export const CREATE_CREDIT_SUCCESS = 'CREATE_CREDIT_SUCCESS';
export const UPDATE_CREDIT_SUCCESS = 'UPDATE_CREDIT_SUCCESS';
export const DELETE_CREDIT_SUCCESS = 'DELETE_CREDIT_SUCCESS';

export const LOAD_DEBITS_SUCCESS = 'LOAD_DEBITS_SUCCESS';
export const CREATE_DEBIT_SUCCESS = 'CREATE_DEBIT_SUCCESS';
export const UPDATE_DEBIT_SUCCESS = 'UPDATE_DEBIT_SUCCESS';
export const DELETE_DEBIT_SUCCESS = 'DELETE_DEBIT_SUCCESS';

export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
